FROM ubuntu:22.04

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

COPY . .

# Compila SOLO il server
RUN gcc server.c protocol.c map.c player.c -o server

EXPOSE 8888

# Comando di avvio del server
CMD ["./server"]