FROM ubuntu:22.04

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

COPY . .

RUN gcc server.c protocol.c map.c player.c -o server

# la flag '-p' serve per far non dare errore se la cartella c'è già.
RUN mkdir -p data 

EXPOSE 8888

CMD ["./server"]