version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ct-server
    ports:
      - "8888:8888"
    networks:
      - ct-net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: ct-client
    networks:
      - ct-net
    stdin_open: true
    tty: true

networks:
  ct-net:
    driver: bridge